### PR TITLE
feat: support location

### PR DESCRIPTION
**Pull request by su-chang**
Related issue: https://github.com/wechaty/wechaty/issues/2250

### CODE REVIEW

**Review by windmemory — APPROVED** [review]
LGTM

**Review by windmemory — DISMISSED** [review]
LGTM

**Comment by su-chang** [comment]
@huan ping

**Review by huan — APPROVED** [review]
LGTM

Thank you very much for adding the Location support!

Please remember:

1. bump the version number, and
2. add docs/comments to new conceptions (like `accuracy`)

next time.

**Pull request merged**
